fixtures:
  symlinks:
    nss_pam_ldapd: "#{source_dir}"
  forge_modules:
    fail_unconfigured: "wcooley/fail_unconfigured"
    stdlib: "puppetlabs/stdlib"
  repositories:
    # Compat for Puppet < 3.0
    # (installing the gem does not seem to suffice)
    'hiera-puppet':
      repo: 'https://github.com/puppetlabs/hiera-puppet.git'
      ref: '1.0.0'
